/**
 * Original author: José Coelho
 * Revised by: Rui Carlos Gonçalves <rcgoncalves.pt@gmail.com>
 */
var Channels = null;

var FantasticHD = 
[
    { id : "24", name : "1MAIS1" },
    { id : "108", name : "ALJAZEERA" },
    { id : "41", name : "ARTE" },
    { id : "49", name : "ARTV / GIGASHOPPING" },
    { id : "77", name : "AXN" },
    { id : "161", name : "AXN HD" },
    { id : "164", name : "AXNBLACK" },
    { id : "148", name : "BABY FIRST" },
    { id : "38", name : "BBC ENTERTAINMENT" },
    { id : "45", name : "BBC WORLD NEWS" },
    { id : "81", name : "BIOGRAPHY CHANNEL" },
    { id : "44", name : "BLOOMBERG" },
    { id : "131", name : "BOOMERANG" },
    { id : "162", name : "BRAVA HD" },
    { id : "28", name : "BVN" },
    { id : "58", name : "C180" },
    { id : "129", name : "CAÇA E PESCA" },
    { id : "19", name : "CANAL HISTÓRIA" },
    { id : "31", name : "CANAL PANDA" },
    { id : "126", name : "CANAL PROGRAMAÇÃO" },
    { id : "142", name : "CANÇÃO NOVA" },
    { id : "32", name : "CARTOON" },
    { id : "52", name : "CNBC" },
    { id : "26", name : "CNN" },
    { id : "121", name : "CUBAVISION INTERNACIONAL" },
    { id : "115", name : "DEUTSCHE WELLE" },
    { id : "22", name : "DISCOVERY CHANNEL" },
    { id : "87", name : "DISCOVERY CIVILIZATION" },
    { id : "88", name : "DISCOVERY SCIENCE" },
    { id : "23", name : "DISCOVERY TRAVEL AND LIVE" },
    { id : "89", name : "DISCOVERY TURBO" },
    { id : "66", name : "DISNEY CHANNEL" },
    { id : "140", name : "DISNEY CINEMAGIC" },
    { id : "147", name : "DISNEY CINEMAGIC HD" },
    { id : "130", name : "E! ENTERTAINMENT" },
    { id : "183", name : "ECONOMICO TV" },
    { id : "184", name : "ECONOMICO TV HD" },
    { id : "97", name : "ESPN CLASSIC" },
    { id : "68", name : "ESPNAHD" },
    { id : "25", name : "EURONEWS" },
    { id : "10", name : "EUROSPORT" },
    { id : "127", name : "EUROSPORT 2" },
    { id : "145", name : "EUROSPORT HD" },
    { id : "79", name : "EUROSPORT NEWS" },
    { id : "78", name : "EXTREME SPORTS CHANNEL" },
    { id : "51", name : "FASHION TV" },
    { id : "47", name : "FASHNHD" },
    { id : "181", name : "FESTA BRAVA" },
    { id : "182", name : "FESTA BRAVA HD" },
    { id : "85", name : "FOX" },
    { id : "114", name : "FOX CRIME" },
    { id : "174", name : "FOX HD" },
    { id : "86", name : "FOX LIFE" },
    { id : "175", name : "FOX LIFE HD" },
    { id : "177", name : "FOX NEXT" },
    { id : "109", name : "FRANCE 24" },
    { id : "132", name : "FRANCE 24 (FR)" },
    { id : "113", name : "FX" },
    { id : "14", name : "HOLLYHD" },
    { id : "13", name : "HOLLYWOOD" },
    { id : "171", name : "HOT" },
    { id : "116", name : "INTER +" },
    { id : "37", name : "M6" },
    { id : "143", name : "MAX" },
    { id : "34", name : "MCM TOP" },
    { id : "50", name : "MEZZO" },
    { id : "125", name : "MOV" },
    { id : "135", name : "MOV HD" },
    { id : "92", name : "MTV DANCE" },
    { id : "91", name : "MTV MUSIC" },
    { id : "36", name : "MTV PORTUGAL" },
    { id : "90", name : "MTV ROCKS" },
    { id : "133", name : "MVM" },
    { id : "169", name : "MYZEN TV COACHING" },
    { id : "168", name : "MYZEN TV MUSIC" },
    { id : "167", name : "MYZEN TV NATURE" },
    { id : "146", name : "NASN/ESPN AMERICA" },
    { id : "59", name : "NATIONAL GEOGRAPHIC" },
    { id : "134", name : "NATIONAL GEOGRAPHIC HD" },
    { id : "178", name : "NBA TV" },
    { id : "46", name : "NHKWLD" },
    { id : "94", name : "NICKELODEON" },
    { id : "20", name : "ODISSEIA" },
    { id : "176", name : "PANDA BIGGS" },
    { id : "112", name : "PFC" },
    { id : "119", name : "PHOENIX CNE" },
    { id : "120", name : "PHOENIX INFO NEWS" },
    { id : "11", name : "PLAYBOY TV" },
    { id : "69", name : "PLBOYHD" },
    { id : "166", name : "POKER CHANNEL" },
    { id : "105", name : "PORTO CANAL" },
    { id : "29", name : "PRESSTV" },
    { id : "30", name : "RECORDNEWS" },
    { id : "149", name : "REGIOES TV" },
    { id : "40", name : "RTL" },
    { id : "27", name : "RTP ÁFRICA" },
    { id : "80", name : "RTP MEMÓRIA" },
    { id : "5", name : "RTP1" },
    { id : "3", name : "RTP2" },
    { id : "64", name : "RTPN" },
    { id : "117", name : "RTR - PLANETA" },
    { id : "165", name : "RUSSIAN TODAY" },
    { id : "144", name : "SET ASIA" },
    { id : "7", name : "SIC" },
    { id : "71", name : "SIC MULHER" },
    { id : "9", name : "SIC NOTÍCIAS" },
    { id : "61", name : "SIC RADICAL" },
    { id : "39", name : "SKY NEWS" },
    { id : "163", name : "SONY TV" },
    { id : "17", name : "SPORT TV 1" },
    { id : "137", name : "SPORT TV 1 HD" },
    { id : "95", name : "SPORT TV 2" },
    { id : "136", name : "SPORT TV 3" },
    { id : "179", name : "SPTV GOLFE" },
    { id : "180", name : "SPTV GOLFE HD" },
    { id : "187", name : "SPTV2HD" },
    { id : "188", name : "SPTV3HD" },
    { id : "189", name : "SPTV4HD" },
    { id : "186", name : "SPTV4HD" },
    { id : "102", name : "SPTVLIHD" },
    { id : "33", name : "TELESUR" },
    { id : "138", name : "TPA INTERNACIONAL" },
    { id : "100", name : "TRAVEL CHANNEL" },
    { id : "124", name : "TV BULGARIA" },
    { id : "54", name : "TV GALICIA" },
    { id : "111", name : "TV GLOBO PORTUGAL" },
    { id : "185", name : "TV MUNDIAL" },
    { id : "101", name : "TV RECORD" },
    { id : "53", name : "TV5 MONDE" },
    { id : "16", name : "TVC1" },
    { id : "18", name : "TVC2" },
    { id : "74", name : "TVC2 HD" },
    { id : "76", name : "TVC3" },
    { id : "84", name : "TVC4" },
    { id : "141", name : "TVC4 HD" },
    { id : "172", name : "TVE 24" },
    { id : "48", name : "TVEI" },
    { id : "8", name : "TVI" },
    { id : "160", name : "TVI 24" },
    { id : "123", name : "TVRI" },
    { id : "118", name : "VESTI" },
    { id : "35", name : "VH1" },
    { id : "93", name : "VH1 CLASSIC" },
    { id : "99", name : "YACHT & SAIL " },
    { id : "57", name : "ZEE TV" },
    { id : "98", name : "ZONE REALITY" },
]

var DigitalHD = 
[
    { id : "24", name : "1MAIS1" },
    { id : "108", name : "ALJAZEERA" },
    { id : "41", name : "ARTE" },
    { id : "49", name : "ARTV / GIGASHOPPING" },
    { id : "77", name : "AXN" },
    { id : "161", name : "AXN HD" },
    { id : "164", name : "AXNBLACK" },
    { id : "38", name : "BBC ENTERTAINMENT" },
    { id : "45", name : "BBC WORLD NEWS" },
    { id : "81", name : "BIOGRAPHY CHANNEL" },
    { id : "44", name : "BLOOMBERG" },
    { id : "162", name : "BRAVA HD" },
    { id : "28", name : "BVN" },
    { id : "58", name : "C180" },
    { id : "129", name : "CAÇA E PESCA" },
    { id : "19", name : "CANAL HISTÓRIA" },
    { id : "31", name : "CANAL PANDA" },
    { id : "126", name : "CANAL PROGRAMAÇÃO" },
    { id : "142", name : "CANÇÃO NOVA" },
    { id : "32", name : "CARTOON" },
    { id : "52", name : "CNBC" },
    { id : "26", name : "CNN" },
    { id : "121", name : "CUBAVISION INTERNACIONAL" },
    { id : "115", name : "DEUTSCHE WELLE" },
    { id : "22", name : "DISCOVERY CHANNEL" },
    { id : "23", name : "DISCOVERY TRAVEL AND LIVE" },
    { id : "66", name : "DISNEY CHANNEL" },
    { id : "140", name : "DISNEY CINEMAGIC" },
    { id : "147", name : "DISNEY CINEMAGIC HD" },
    { id : "183", name : "ECONOMICO TV" },
    { id : "184", name : "ECONOMICO TV HD" },
    { id : "25", name : "EURONEWS" },
    { id : "10", name : "EUROSPORT" },
    { id : "127", name : "EUROSPORT 2" },
    { id : "85", name : "FOX" },
    { id : "174", name : "FOX HD" },
    { id : "86", name : "FOX LIFE" },
    { id : "175", name : "FOX LIFE HD" },
    { id : "109", name : "FRANCE 24" },
    { id : "132", name : "FRANCE 24 (FR)" },
    { id : "14", name : "HOLLYHD" },
    { id : "13", name : "HOLLYWOOD" },
    { id : "171", name : "HOT" },
    { id : "116", name : "INTER +" },
    { id : "37", name : "M6" },
    { id : "143", name : "MAX" },
    { id : "34", name : "MCM TOP" },
    { id : "50", name : "MEZZO" },
    { id : "125", name : "MOV" },
    { id : "135", name : "MOV HD" },
    { id : "36", name : "MTV PORTUGAL" },
    { id : "133", name : "MVM" },
    { id : "169", name : "MYZEN TV COACHING" },
    { id : "168", name : "MYZEN TV MUSIC" },
    { id : "167", name : "MYZEN TV NATURE" },
    { id : "59", name : "NATIONAL GEOGRAPHIC" },
    { id : "46", name : "NHKWLD" },
    { id : "20", name : "ODISSEIA" },
    { id : "176", name : "PANDA BIGGS" },
    { id : "112", name : "PFC" },
    { id : "119", name : "PHOENIX CNE" },
    { id : "120", name : "PHOENIX INFO NEWS" },
    { id : "11", name : "PLAYBOY TV" },
    { id : "69", name : "PLBOYHD" },
    { id : "105", name : "PORTO CANAL" },
    { id : "29", name : "PRESSTV" },
    { id : "30", name : "RECORDNEWS" },
    { id : "149", name : "REGIOES TV" },
    { id : "40", name : "RTL" },
    { id : "27", name : "RTP ÁFRICA" },
    { id : "80", name : "RTP MEMÓRIA" },
    { id : "5", name : "RTP1" },
    { id : "3", name : "RTP2" },
    { id : "64", name : "RTPN" },
    { id : "117", name : "RTR - PLANETA" },
    { id : "144", name : "SET ASIA" },
    { id : "7", name : "SIC" },
    { id : "71", name : "SIC MULHER" },
    { id : "9", name : "SIC NOTÍCIAS" },
    { id : "61", name : "SIC RADICAL" },
    { id : "39", name : "SKY NEWS" },
    { id : "163", name : "SONY TV" },
    { id : "17", name : "SPORT TV 1" },
    { id : "137", name : "SPORT TV 1 HD" },
    { id : "95", name : "SPORT TV 2" },
    { id : "136", name : "SPORT TV 3" },
    { id : "179", name : "SPTV GOLFE" },
    { id : "180", name : "SPTV GOLFE HD" },
    { id : "187", name : "SPTV2HD" },
    { id : "188", name : "SPTV3HD" },
    { id : "189", name : "SPTV4HD" },
    { id : "186", name : "SPTV4HD" },
    { id : "102", name : "SPTVLIHD" },
    { id : "33", name : "TELESUR" },
    { id : "138", name : "TPA INTERNACIONAL" },
    { id : "124", name : "TV BULGARIA" },
    { id : "54", name : "TV GALICIA" },
    { id : "111", name : "TV GLOBO PORTUGAL" },
    { id : "185", name : "TV MUNDIAL" },
    { id : "101", name : "TV RECORD" },
    { id : "53", name : "TV5 MONDE" },
    { id : "16", name : "TVC1" },
    { id : "18", name : "TVC2" },
    { id : "74", name : "TVC2 HD" },
    { id : "76", name : "TVC3" },
    { id : "84", name : "TVC4" },
    { id : "141", name : "TVC4 HD" },
    { id : "172", name : "TVE 24" },
    { id : "48", name : "TVEI" },
    { id : "8", name : "TVI" },
    { id : "160", name : "TVI 24" },
    { id : "123", name : "TVRI" },
    { id : "118", name : "VESTI" },
    { id : "35", name : "VH1" },
    { id : "57", name : "ZEE TV" },
]

var SeleccaoDigital = 
[
    { id : "49", name : "ARTV / GIGASHOPPING" },
    { id : "31", name : "CANAL PANDA" },
    { id : "10", name : "EUROSPORT" },
    { id : "13", name : "HOLLYWOOD" },
    { id : "176", name : "PANDA BIGGS" },
    { id : "105", name : "PORTO CANAL" },
    { id : "80", name : "RTP MEMÓRIA" },
    { id : "5", name : "RTP1" },
    { id : "3", name : "RTP2" },
    { id : "64", name : "RTPN" },
    { id : "7", name : "SIC" },
    { id : "9", name : "SIC NOTÍCIAS" },
    { id : "17", name : "SPORT TV 1" },
    { id : "137", name : "SPORT TV 1 HD" },
    { id : "95", name : "SPORT TV 2" },
    { id : "136", name : "SPORT TV 3" },
    { id : "179", name : "SPTV GOLFE" },
    { id : "180", name : "SPTV GOLFE HD" },
    { id : "187", name : "SPTV2HD" },
    { id : "188", name : "SPTV3HD" },
    { id : "189", name : "SPTV4HD" },
    { id : "186", name : "SPTV4HD" },
    { id : "102", name : "SPTVLIHD" },
    { id : "101", name : "TV RECORD" },
    { id : "8", name : "TVI" },
    { id : "160", name : "TVI 24" },
]

var BaseSportTV =
[
    { id : "49", name : "ARTV / GIGASHOPPING" },
    { id : "81", name : "BIOGRAPHY CHANNEL" },
    { id : "129", name : "CAÇA E PESCA" },
    { id : "19", name : "CANAL HISTÓRIA" },
    { id : "31", name : "CANAL PANDA" },
    { id : "126", name : "CANAL PROGRAMAÇÃO" },
    { id : "32", name : "CARTOON" },
    { id : "22", name : "DISCOVERY CHANNEL" },
    { id : "23", name : "DISCOVERY TRAVEL AND LIVE" },
    { id : "66", name : "DISNEY CHANNEL" },
    { id : "140", name : "DISNEY CINEMAGIC" },
    { id : "147", name : "DISNEY CINEMAGIC HD" },
    { id : "10", name : "EUROSPORT" },
    { id : "13", name : "HOLLYWOOD" },
    { id : "171", name : "HOT" },
    { id : "36", name : "MTV PORTUGAL" },
    { id : "20", name : "ODISSEIA" },
    { id : "112", name : "PFC" },
    { id : "11", name : "PLAYBOY TV" },
    { id : "5", name : "RTP1" },
    { id : "3", name : "RTP2" },
    { id : "64", name : "RTPN" },
    { id : "7", name : "SIC" },
    { id : "9", name : "SIC NOTÍCIAS" },
    { id : "17", name : "SPORT TV 1" },
    { id : "137", name : "SPORT TV 1 HD" },
    { id : "95", name : "SPORT TV 2" },
    { id : "136", name : "SPORT TV 3" },
    { id : "186", name : "SPTV4HD" },
    { id : "111", name : "TV GLOBO PORTUGAL" },
    { id : "101", name : "TV RECORD" },
    { id : "16", name : "TVC1" },
    { id : "18", name : "TVC2" },
    { id : "76", name : "TVC3" },
    { id : "84", name : "TVC4" },
    { id : "141", name : "TVC4 HD" },
    { id : "8", name : "TVI" },
    { id : "160", name : "TVI 24" },
    { id : "35", name : "VH1" },
]

var SegundaHabitacao = 
[
    { id : "49", name : "ARTV / GIGASHOPPING" },
    { id : "77", name : "AXN" },
    { id : "148", name : "BABY FIRST" },
    { id : "38", name : "BBC ENTERTAINMENT" },
    { id : "45", name : "BBC WORLD NEWS" },
    { id : "81", name : "BIOGRAPHY CHANNEL" },
    { id : "44", name : "BLOOMBERG" },
    { id : "129", name : "CAÇA E PESCA" },
    { id : "19", name : "CANAL HISTÓRIA" },
    { id : "31", name : "CANAL PANDA" },
    { id : "126", name : "CANAL PROGRAMAÇÃO" },
    { id : "142", name : "CANÇÃO NOVA" },
    { id : "32", name : "CARTOON" },
    { id : "52", name : "CNBC" },
    { id : "26", name : "CNN" },
    { id : "22", name : "DISCOVERY CHANNEL" },
    { id : "87", name : "DISCOVERY CIVILIZATION" },
    { id : "88", name : "DISCOVERY SCIENCE" },
    { id : "23", name : "DISCOVERY TRAVEL AND LIVE" },
    { id : "89", name : "DISCOVERY TURBO" },
    { id : "66", name : "DISNEY CHANNEL" },
    { id : "140", name : "DISNEY CINEMAGIC" },
    { id : "130", name : "E! ENTERTAINMENT" },
    { id : "25", name : "EURONEWS" },
    { id : "10", name : "EUROSPORT" },
    { id : "79", name : "EUROSPORT NEWS" },
    { id : "78", name : "EXTREME SPORTS CHANNEL" },
    { id : "51", name : "FASHION TV" },
    { id : "85", name : "FOX" },
    { id : "114", name : "FOX CRIME" },
    { id : "86", name : "FOX LIFE" },
    { id : "109", name : "FRANCE 24" },
    { id : "113", name : "FX" },
    { id : "13", name : "HOLLYWOOD" },
    { id : "171", name : "HOT" },
    { id : "37", name : "M6" },
    { id : "34", name : "MCM TOP" },
    { id : "50", name : "MEZZO" },
    { id : "125", name : "MOV" },
    { id : "92", name : "MTV DANCE" },
    { id : "91", name : "MTV MUSIC" },
    { id : "36", name : "MTV PORTUGAL" },
    { id : "90", name : "MTV ROCKS" },
    { id : "146", name : "NASN/ESPN AMERICA" },
    { id : "59", name : "NATIONAL GEOGRAPHIC" },
    { id : "94", name : "NICKELODEON" },
    { id : "20", name : "ODISSEIA" },
    { id : "176", name : "PANDA BIGGS" },
    { id : "112", name : "PFC" },
    { id : "11", name : "PLAYBOY TV" },
    { id : "105", name : "PORTO CANAL" },
    { id : "40", name : "RTL" },
    { id : "27", name : "RTP ÁFRICA" },
    { id : "80", name : "RTP MEMÓRIA" },
    { id : "5", name : "RTP1" },
    { id : "3", name : "RTP2" },
    { id : "64", name : "RTPN" },
    { id : "7", name : "SIC" },
    { id : "71", name : "SIC MULHER" },
    { id : "9", name : "SIC NOTÍCIAS" },
    { id : "61", name : "SIC RADICAL" },
    { id : "39", name : "SKY NEWS" },
    { id : "163", name : "SONY TV" },
    { id : "17", name : "SPORT TV 1" },
    { id : "137", name : "SPORT TV 1 HD" },
    { id : "95", name : "SPORT TV 2" },
    { id : "136", name : "SPORT TV 3" },
    { id : "179", name : "SPTV GOLFE" },
    { id : "187", name : "SPTV2HD" },
    { id : "186", name : "SPTV4HD" },
    { id : "102", name : "SPTVLIHD" },
    { id : "100", name : "TRAVEL CHANNEL" },
    { id : "54", name : "TV GALICIA" },
    { id : "111", name : "TV GLOBO PORTUGAL" },
    { id : "101", name : "TV RECORD" },
    { id : "53", name : "TV5 MONDE" },
    { id : "16", name : "TVC1" },
    { id : "18", name : "TVC2" },
    { id : "76", name : "TVC3" },
    { id : "84", name : "TVC4" },
    { id : "141", name : "TVC4 HD" },
    { id : "48", name : "TVEI" },
    { id : "8", name : "TVI" },
    { id : "160", name : "TVI 24" },
    { id : "35", name : "VH1" },
    { id : "93", name : "VH1 CLASSIC" },
    { id : "99", name : "YACHT & SAIL " },
    { id : "98", name : "ZONE REALITY" },
]

var Base =
[
    { id : "49", name : "ARTV / GIGASHOPPING" },
    { id : "81", name : "BIOGRAPHY CHANNEL" },
    { id : "129", name : "CAÇA E PESCA" },
    { id : "19", name : "CANAL HISTÓRIA" },
    { id : "31", name : "CANAL PANDA" },
    { id : "126", name : "CANAL PROGRAMAÇÃO" },
    { id : "32", name : "CARTOON" },
    { id : "22", name : "DISCOVERY CHANNEL" },
    { id : "23", name : "DISCOVERY TRAVEL AND LIVE" },
    { id : "66", name : "DISNEY CHANNEL" },
    { id : "140", name : "DISNEY CINEMAGIC" },
    { id : "10", name : "EUROSPORT" },
    { id : "13", name : "HOLLYWOOD" },
    { id : "171", name : "HOT" },
    { id : "36", name : "MTV PORTUGAL" },
    { id : "20", name : "ODISSEIA" },
    { id : "176", name : "PANDA BIGGS" },
    { id : "112", name : "PFC" },
    { id : "11", name : "PLAYBOY TV" },
    { id : "5", name : "RTP1" },
    { id : "3", name : "RTP2" },
    { id : "64", name : "RTPN" },
    { id : "7", name : "SIC" },
    { id : "9", name : "SIC NOTÍCIAS" },
    { id : "163", name : "SONY TV" },
    { id : "17", name : "SPORT TV 1" },
    { id : "137", name : "SPORT TV 1 HD" },
    { id : "95", name : "SPORT TV 2" },
    { id : "136", name : "SPORT TV 3" },
    { id : "179", name : "SPTV GOLFE" },
    { id : "187", name : "SPTV2HD" },
    { id : "186", name : "SPTV4HD" },
    { id : "102", name : "SPTVLIHD" },
    { id : "111", name : "TV GLOBO PORTUGAL" },
    { id : "101", name : "TV RECORD" },
    { id : "16", name : "TVC1" },
    { id : "18", name : "TVC2" },
    { id : "76", name : "TVC3" },
    { id : "84", name : "TVC4" },
    { id : "141", name : "TVC4 HD" },
    { id : "8", name : "TVI" },
    { id : "160", name : "TVI 24" },
    { id : "35", name : "VH1" },
]
